### ISSUE TITLE
Badges System

### ISSUE THREAD

**Issue by Tougrel** [ShadyDevelopers/Aura#28]
Completly revamp the current badges system

### Badges:
- [x] Developer
- [x] Staff Member *removed in favor of ShadowCT badge*
- [x] Beta *rework current beta (fire) icon*
- [x] Contributor *you can get this by opening issues and feature requests here on github*
- [x] Verified 
- [x] Elite *season and event winners*
- [x] Season Winner
- [x] Premium *rework current premium (meteor) icon*
- [x] ShadowCT badge *all shadowct staff members*

### Dev Changes
- [ ] Move badges to the new user table
- [x] Add badges to web profiles

**Comment by tougrel** [comment]
The badges has been replaced with the new **Roles** system. More information will be revealed in 2023
